version: '2'
services:
 redis:
  image: redis
  ports:
    - "6379:6379"
 ambassador:
  image: cpuguy83/docker-grand-ambassador
  volumes:
   - "/var/run/docker.sock:/docker.sock"
  command: "-name docker_simpleidserver_1"
 simpleidserver:
  build:
   dockerfile: Dockerfile-IdServer
   context: .
  ports:
   - "5443:5443"
  links:
   - postgresql
   - configuration
   - "ambassador:simpleidserver"
   - elasticsearch
   - redis
  depends_on:
   - "postgresql"
  environment:
   - DB_ALIAS=postgresql
   - DB_PORT=5432
 uma:
  build:
   dockerfile: Dockerfile-Uma-IdServer-Https
   context: .
  ports:
   - "5445:5445"
  links:
   - postgresql_uma:postgresql
   - "ambassador:simpleidserver"
   - elasticsearch
   - redis
  depends_on:
   - "postgresql_uma"
   - elasticsearch
  environment:
   - DB_ALIAS=postgresql
   - DB_PORT=5432
 manager:
  build:
   dockerfile: Dockerfile-Manager-IdServer
   context: .
  links:
   - postgresql
   - "ambassador:simpleidserver"
   - elasticsearch
   - redis
  depends_on:
   - "postgresql"
   - elasticsearch
  environment:
   - DB_ALIAS=postgresql
   - DB_PORT=5432
 configuration:
  build:
   dockerfile: Dockerfile-Configuration-IdServer
   context: .
  links:
   - postgresql_configuration:postgresql
   - "ambassador:simpleidserver"
   - elasticsearch
   - redis
   - postgresql:postgresql_idserver
  depends_on:
   - "postgresql_configuration"
   - elasticsearch
  environment:
   - DB_ALIAS=postgresql
   - DB_PORT=5432
 website:
  build:
   dockerfile: Dockerfile-WebSite
   context: .
  ports:
   - "4200:4200"
  links:
   - "ambassador:simpleidserver"   
   - uma:uma
  environment:
   - SERVER=idserver
 websiteapi:
  build:
   dockerfile: Dockerfile-WebSiteApi
   context: .
  ports:
   - "5444:5444"
  links:
   - "ambassador:simpleidserver"
   - uma:uma
   - manager:manager
   - configuration:configuration
   - mongo:mongo
  depends_on:
   - "mongo"
  environment:
   - INTROSPECTION_CLIENT_ID=website_api
   - INTROSPECTION_CLIENT_SECRET=website_api
 postgresql:
  image: postgres
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=password
   - POSTGRES_DB=postgres
 postgresql_uma:
  image: postgres
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=password
   - POSTGRES_DB=postgres
 postgresql_configuration:
  image: postgres
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=password
   - POSTGRES_DB=postgres
 mongo:
  image: mongo
 elasticsearch:
  image: elasticsearch
  ports:
   - 9200:9200
 kibana:
  image: kibana
  ports:
   - 5601:5601
  environment:
   - ELASTICSEARCH_URL=http://elasticsearch:9200