version: '2'
services:
 ambassador:
  image: cpuguy83/docker-grand-ambassador
  volumes:
   - "/var/run/docker.sock:/docker.sock"
  command: "-name docker_simpleidserver_1"
 simpleidserver:
  build:
   dockerfile: Dockerfile-Authorization
   context: .
  ports:
   - "5000:5000"
  links:
   - postgresql
   - configuration
  depends_on:
   - "postgresql"
  environment:
   - DB_ALIAS=postgresql
   - DB_PORT=5432
 uma:
  build:
   dockerfile: Dockerfile-Uma
   context: .
  ports:
   - "5001:5001"
  links:
   - postgresql_uma:postgresql
   - "ambassador:simpleidserver"
  depends_on:
   - "postgresql_uma"
  environment:
   - DB_ALIAS=postgresql
   - DB_PORT=5432
 manager:
  build:
   dockerfile: Dockerfile-Manager
   context: .
  ports:
   - "5002:5002"
  links:
   - postgresql
   - "ambassador:simpleidserver"
  depends_on:
   - "postgresql"
  environment:
   - DB_ALIAS=postgresql
   - DB_PORT=5432
 configuration:
  build:
   dockerfile: Docker-Configuration
   context: .
  ports:
   - "5004:5004"
  links:
   - postgresql_configuration:postgresql
   - "ambassador:simpleidserver"
  depends_on:
   - "postgresql_configuration"
  environment:
   - DB_ALIAS=postgresql
   - DB_PORT=5432
 postgresql:
  image: postgres
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=password
   - POSTGRES_DB=postgres
 postgresql_uma:
  image: postgres
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=password
   - POSTGRES_DB=postgres
 postgresql_configuration:
  image: postgres
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=password
   - POSTGRES_DB=postgres